version: "3.7"
services:
  ui:
    container_name: ui_container
    build: ./
    volumes:
      - "./:/app"
      - "/app/node_modules"
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true